threading.py:1032:SB
--------------------------------------------------------------------
Last Page: [WARNING! Browser Not Open!]
 Duration: 26.70s
  Browser: Chrome 133.0.6943.141 / headless
   Driver: chromedriver 133.0.6943.141
Timestamp: 1743354106  (Unix Timestamp)
     Date: Sunday, March 30, 2025
     Time: 1:01:46 PM  (EDT, UTC-04:00)
--------------------------------------------------------------------
Traceback:
  File "/home/vertefra/Desktop/spending-app/websearch/test/agent_test.py", line 11, in <module>
    asyncio.run(test_query())
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 193, in run
    with Runner(debug=debug, loop_factory=loop_factory) as runner:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 62, in __exit__
    self.close()
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 72, in close
    loop.run_until_complete(
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/base_events.py", line 673, in run_until_complete
    self.run_forever()
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/base_events.py", line 640, in run_forever
    self._run_once()
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/base_events.py", line 1954, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vertefra/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: 